### ISSUE TITLE
Wayland Gnome upon opening any GUI app

### ISSUE THREAD

**Issue by jerz4lunch** [NyarchLinux/NyarchLinux#29] opened 2024-06-08 22:59 UTC
I try to start any app and gnome-shell crashes.  I have tried kitty terminal, regular terminal, and Firefox, all with same result.  Issue does not occur when running under Xorg.  I have attached the core dump from journalctl below.  This happened after running an update with `sudo pacman -Syu` on the kitty terminal.

[gnome-shell.coredump.txt](https://github.com/user-attachments/files/15749823/gnome-shell.coredump.txt)

**Comment by FrancescoCaracciolo** [comment] 2024-06-08 23:06
Can you try disabling extensions? Also, can you describe the hardware you are running Nyarch on?

**Comment by jerz4lunch** [comment] 2024-06-08 23:37
Extensions?  I'm not sure how to find that.  I know how to use vanilla Arch, but I'm trying to fix it for a friend.  Would the output of the dmidecode help with IDing the hardware?

**Comment by FrancescoCaracciolo** [comment] 2024-06-08 23:39
Just give me general information, like cpu, ram, gpu

**Comment by jerz4lunch** [comment] 2024-06-08 23:50
Output of respective commands:

[dmidecode.txt](https://github.com/user-attachments/files/15749901/dmidecode.txt)
[gpu (lspci | grep VGA).txt](https://github.com/user-attachments/files/15749902/gpu.lspci._pipe_.grep.VGA.txt)
[lscpu.txt](https://github.com/user-attachments/files/15749903/lscpu.txt)
[ram (free -h).txt](https://github.com/user-attachments/files/15749904/ram.free.-h.txt)

**Comment by jerz4lunch** [comment] 2024-06-08 23:52
Newbie to GitHub.  Closed by mistake.

**Comment by FrancescoCaracciolo** [comment] 2024-06-08 23:54
The hardware looks pretty good, it should not be the problem here. 
I think the issue is not much on Nyarch side but more on Gnome or Arch side

**Comment by FrancescoCaracciolo** [comment] 2024-11-02 17:06
Should be fixed from next version

**Closed by FrancescoCaracciolo** 2024-11-02 17:06 UTC
Labels: bug
